id: P004270
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:06:22.108030
source_metadata:
  id: bdr:W1KG4520
  title: སུམ་ཅུ་པའི་རྣམ་བཤད།
  author: ''
  volumes:
    323b5d242b0a421cb2edbf9b33abdbe0:
      image_group_id: I1KG4539
      title: ''
      volume_number: 1
      total_pages: 212
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
