id: I9B84EEB7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:21:48+00:00'
last_modified: '2022-06-07T21:34:17.272701+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4520
  title: སུམ་ཅུ་པའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    921D:
      image_group_id: I1KG4539
      title: ''
      total_pages: 212
      order: 1
      base_file: 921D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
