id: I9B84EEB7
legacy_id: P004270
ocr_import_info:
  bdrc_scan_id: W1KG4520
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:20:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:12:37.778982+00:00'
last_modified: 2022-08-27 16:12:59.984711
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4520
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4520
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སུམ་ཅུ་པའི་རྣམ་བཤད།
  author: འཇམ་པ་ཆོས་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8443156802130443
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG4539:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4539
      total_pages: 212
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4539.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8443156802130443
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
